name: Deploy to Pi

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Load SSH key
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.PI_DEPLOY_KEY }}

      - name: Pull and deploy
        run: |
          echo "Running git pull on $PI_HOST…"
          ssh -o StrictHostKeyChecking=no \
              -p 2222 \
              ${{ secrets.PI_USER }}@${{ secrets.PI_HOST }} \
              "cd /var/www/nickesselman.nl/html && git pull origin main"
